### ISSUE TITLE
Flash fix

### ISSUE THREAD

**Issue by Decotron99** [PiSaucer/boredhtml#9]
There is a thing called ruffle: https://github.com/ruffle-rs/ruffle/
it allows you to use flash via emulator it is really easy to use and lets you have flash even though its dead 😄

**Comment by PiSaucer** [comment]
I started to add that to some of the pages. I am also adding breadcrumbs and cleaning up some of the 2-year old code.

**Comment by Decotron99** [comment]
cool

**Comment by Decotron99** [comment]
i really like this site also how did you add mari0 its in love2d?

**Comment by PiSaucer** [comment]
I just took the mari0 from [tannerrogalsky.github.com](https://github.com/TannerRogalsky/tannerrogalsky.github.com/tree/master/mari0) a couple of years ago. I don't think there has been a major update to worry about compiling it. It uses the [love.js ](https://github.com/TannerRogalsky/love.js) which is TannerRogalsky's LÖVE ported to the web using Emscripten. If you want to talk more you can join the official [Discord Server](https://discord.gg/7qTNdXd) although it's not extremely active.
